### ISSUE TITLE
Why the created image is bigger than original ?

### ISSUE THREAD

**Issue by alexis-mateo** [x011/SecretPixel#1]
Hello,
I want to use your lib in a school project, but I have a little question about the size of the resulting image.

For example, I have a PNG image with size of 2,52 MB (2 646 581 bytes). When I run your python code the created image has the size of 2,64 MB (2 778 949 bytes). 

Why the size of image increase of 0,10 MB ?

Thanks for your response and your lib ! :)

**Comment by x011** [comment]
Hello,
The final image is usually larger than the original because it needs to contain the hidden file inside.
