### ISSUE TITLE
Ciphertext length must be equal to key size.

### ISSUE THREAD

**Issue by techpolymath** [x011/SecretPixel#3]
Running on Apple M2 Max
SecretPixel was installed and ran in venv.

Hides secret fine, but when attempting to extract...

File "/Users/patrick/test/SecretPixel/secret_pixel.py", line 69, in decrypt_data
    session_key = private_key.decrypt(
                  ^^^^^^^^^^^^^^^^^^^^
ValueError: Ciphertext length must be equal to key size.

**Comment by techpolymath** [comment]
Issue was with Gradio Component image conversion not SecretPixel.

**Comment by vaygr** [comment]
I have the same issue with the file that worked just fine until recently.

**Comment by vaygr** [comment]
I have the same issue with the file that worked just fine until recently. @x011 any idea?

**Comment by vaygr** [comment]
Turns out the issue was introduced by numpy 2. I raised #4 as a potential fix.
